In [225]:
import numpy as np
from scipy.stats import skewnorm, skew
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

def simulate_data(classes, n_vars, n, max_mu, max_sigma, max_skew):
    #The multivariate skew normal number generator
    def rng(mu, sigma, skew, n=1):
        k = len(mu)
        if not (k == len(sigma) and k ==len(skew)): 
            raise Exception("Mu, Sigma and Skew should be same length")

        data = np.zeros((int(n),k))

        for i in range(k):
            data[:,i] = skewnorm.rvs(skew[i], loc=mu[i], scale=sigma[i], size=int(n)) 

        return data
    
    if(np.sum(classes) != 1):
        raise Exception("Classes dont sum up to 1")
        
    n_classes = len(classes)
    sigma = np.random.randint(1,max_sigma,n_vars)
    skew = np.random.randint(-max_skew,max_skew,n_vars)
    mu =  np.random.randint(-max_mu, max_mu, (n_classes, n_vars))
    
    n_obs_class = np.round(np.dot(classes,n))
    
    print(n_obs_class)
    
    data = np.zeros((int(np.sum(n_obs_class)),n_vars+1))
    for i in range(n_classes):
        #calculate indexes
        start = int(np.sum(n_obs_class[0:i]))
        end = int(np.sum(n_obs_class[0:i+1]))
        
        #set the data
        data[start:end,0] = i
        data[start:end,1:] = rng(mu[i,:], sigma, skew, n_obs_class[i])
        
    X = data[:,1:]
    y = data[:,0]
    
    columns = ["x"+str(x) for x in range(n_vars + 1)]
    columns[0] = "class"
    
    df = pd.DataFrame(data,columns=columns)
    df["class"] = df["class"].astype(int)
    return X,y, df



#parameters
classes = [0.2, 0.5, 0.3] #percentages
n_vars = 5
n = 1000
max_mu = 20
max_sigma = 10
max_skew = 7
np.random.seed(12345)

#generate data
X,y, df = simulate_data(classes, n_vars, n, max_mu, max_sigma, max_skew)

display(df.groupby(["class"]).agg(["count", "mean", "var"]))

#make train and test set
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)


[200. 500. 300.]


x1                         x2                          x3            \
      count       mean       var count       mean        var count      mean   
class                                                                          
0       200  -8.420708  3.680863   200  12.016630  12.877729   200 -5.634599   
1       500  -9.320480  3.537210   500  -5.265588  14.155351   500 -4.657535   
2       300 -15.498680  3.714898   300  23.961645  12.464764   300  1.343592   

                   x4                          x5                        
            var count       mean        var count       mean        var  
class                                                                    
0      1.674577   200 -13.963915  16.111069   200 -14.026780  13.722221  
1      1.608868   500  -5.162992  15.115465   500  13.133143  13.974816  
2      1.553242   300   6.791279  17.778164   300   6.168479  14.357211

In [ ]:
    
    

# display(np.cov(data.T))




# plt.plot(x, y, 'x')
# plt.axis('equal')
# plt.show()


# plt.hist(x)
# plt.hist(y)
# # plt.hist(z)

# from mpl_toolkits import mplot3d
# fig = plt.figure()
# ax = plt.axes(projection='3d')
# ax.scatter3D(x, y, z, c=z);

In [156]:
np.random.seed(1234)
data = np.random.randint(0,10,(3,3))
display(data)
data[:,1:]

array([[3, 6, 5],
       [4, 8, 9],
       [1, 7, 9]])

array([[6, 5],
       [8, 9],
       [7, 9]])