In [170]:
import numpy as np
from scipy.stats import skewnorm, skew
import matplotlib.pyplot as plt
import pandas as pd


#parameters
classes = [0.2, 0.5, 0.3] #percentages
n_vars = 10
n = 1000
max_mu = 20
max_sigma = 10
max_skew = 7
np.random.seed(12345)


def simulate_data(classes, n_vars, n, max_mu, max_sigma, max_skew):
    #The multivariate skew normal number generator
    def rng(mu, sigma, skew, n=1):
        k = len(mu)
        if not (k == len(sigma) and k ==len(skew)): 
            raise Exception("Mu, Sigma and Skew should be same length")

        data = np.zeros((int(n),k))

        for i in range(k):
            data[:,i] = skewnorm.rvs(skew[i], loc=mu[i], scale=sigma[i], size=int(n)) 

        return data
    
    if(np.sum(classes) != 1):
        raise Exception("Classes dont sum up to 1")
        
    n_classes = len(classes)
    sigma = np.random.randint(1,max_sigma,n_vars)
    skew = np.random.randint(-max_skew,max_skew,n_vars)
    mu =  np.random.randint(-max_mu, max_mu, (n_classes, n_vars))
    
    n_obs_class = np.round(np.dot(classes,n))
    
    print(n_obs_class)
    
    data = np.zeros((int(np.sum(n_obs_class)),n_vars+1))
    for i in range(n_classes):
        #calculate indexes
        start = int(np.sum(n_obs_class[0:i]))
        end = int(np.sum(n_obs_class[0:i+1]))
        
        #set the data
        data[start:end,0] = i
        data[start:end,1:] = rng(mu[i,:], sigma, skew, n_obs_class[i])
        
    X = data[:,1:]
    y = data[:,0]
    
    columns = ["x"+str(x) for x in range(n_vars + 1)]
    columns[0] = "class"
    
    df = pd.DataFrame(data,columns=columns)

    return X,y, df

X,y, df = simulate_data(classes, n_vars, n, max_mu, max_sigma, max_skew)
# data = X.join(pd.Series(y, name='class'))

display(df)


[200. 500. 300.]


class         x1         x2        x3         x4         x5         x6  \
0      0.0 -14.013540  15.677506  1.829222   4.949057  13.254788  14.347968   
1      0.0 -10.042260  12.523824  1.747542  11.727868  16.894793  14.343651   
2      0.0 -15.107836  16.174970  2.934717  10.046998  11.393264  15.722016   
3      0.0 -11.811799  18.342785  0.445583   9.465393  17.918978  18.181107   
4      0.0 -12.723650  11.638859  2.347462  10.760957  16.959377  15.480157   
5      0.0 -12.052482  17.529102 -0.274735  11.261768  13.312943  15.117240   
6      0.0 -16.985712  18.475640  3.400556  10.813930  12.169179  12.895663   
7      0.0 -18.446821  13.954067  2.142966   7.725867  13.621330  16.439200   
8      0.0 -19.547022  12.909681  0.718306  16.682876  12.799038  15.513667   
9      0.0 -10.251888  17.468064  2.448775  12.867457  17.179283  14.221798   
10     0.0  -7.864000  15.426176  2.867126  13.550714  19.375682  15.676526   
11     0.0 -14.142872  16.999919  0.804749  12.005156  12.290981  14.201402   
12     0.0 -19.818230  13.965789  1.428114  11.368761  18.747442  13.128032   
13     0.0 -20.395039  17.513518  1.889027  11.286804  14.261194  15.490960   
14     0.0 -14.618715  19.774147  3.144942  15.243676  14.131300  16.598509   
15     0.0 -16.362633  17.745554  2.497906   8.243015  14.839941  14.208774   
16     0.0 -11.710672  12.109464  2.425155   9.565149  23.527583  17.550298   
17     0.0 -17.517701  14.892516  0.692999   8.438148  19.476256  14.454114   
18     0.0 -17.485215  17.579926  0.589669  11.358743  12.327297  17.203734   
19     0.0 -15.757866  12.299577  2.213603   5.488386  16.920689  16.790743   
20     0.0 -12.913695  12.811053  1.958122  13.718688   9.484283  13.773599   
21     0.0 -13.505884  11.961629  1.255020  16.013125  14.520158  14.338853   
22     0.0 -15.376188  14.036510  2.713870   9.785159  15.605469  17.372493   
23     0.0 -14.601271  16.009099  1.836731  13.687763  11.335488  13.181396   
24     0.0 -14.660569  13.664167  1.328622  10.543897  20.157408  14.848915   
25     0.0 -13.928054  12.207865  2.924050   8.783512  13.100220  14.727695   
26     0.0 -14.348188  16.472819  0.148636  14.883640  15.732189  12.536005   
27     0.0 -14.468952  10.715711  1.826250  15.035607  16.814723  14.049592   
28     0.0 -15.501719  12.205305  1.695915   9.209939  25.223112  14.939761   
29     0.0 -12.705365  13.385373  0.954258  12.913817  13.987932  15.776236   
..     ...        ...        ...       ...        ...        ...        ...   
970    2.0   9.713267 -22.661056 -1.893340  -7.231150   0.494779  -0.169660   
971    2.0  10.525199 -19.122224 -3.778816  -8.072267   4.927760  -3.402684   
972    2.0  11.364640 -20.766141 -1.973388  -2.085114  -1.571862  -1.176299   
973    2.0  11.999675 -16.195042 -4.071525  -4.724608  -0.262483   2.144871   
974    2.0  10.272425 -22.917117 -1.844499  -1.200064  -3.267031  -0.248704   
975    2.0  16.174874 -17.865496 -2.726470  -0.753061  -7.240561  -0.773806   
976    2.0  13.878573 -13.923190 -0.916080  -1.772827  -3.033988  -2.537668   
977    2.0  11.515726 -23.478873 -3.203349  -9.094788  -0.027615  -0.633870   
978    2.0  13.804618 -15.066366 -0.731908  -7.042848  -4.133610  -3.295553   
979    2.0  14.443762 -21.656319 -1.804272  -6.289803  -3.678725  -2.581851   
980    2.0  10.790632 -24.460511 -1.295086  -5.253232   0.278734  -3.252114   
981    2.0  13.413362 -19.574866 -1.875425  -4.839044  -4.986234  -2.851753   
982    2.0   9.478507 -18.963500 -4.961625  -6.708827  -4.838554  -2.817785   
983    2.0  11.502662 -33.341156 -2.773631 -11.228552  -4.308689  -0.616584   
984    2.0  12.495511 -17.062541 -2.355579  -3.529081  -5.462445  -1.110220   
985    2.0  15.663868 -19.070066 -2.485950  -5.660716  -3.882228  -3.696631   
986    2.0  10.332171 -16.290195 -1.863127 -11.357101  -4.567860   1.144819   
987    2.0  11.705110 -19.411500 -2.344587  -4.453414   3.121639  -0.754480   
988    2.0  15.805677 -23.332088 -3.304010  -5.765011  

In [ ]:
    
    

# display(np.cov(data.T))




# plt.plot(x, y, 'x')
# plt.axis('equal')
# plt.show()


# plt.hist(x)
# plt.hist(y)
# # plt.hist(z)

# from mpl_toolkits import mplot3d
# fig = plt.figure()
# ax = plt.axes(projection='3d')
# ax.scatter3D(x, y, z, c=z);

In [156]:
np.random.seed(1234)
data = np.random.randint(0,10,(3,3))
display(data)
data[:,1:]

array([[3, 6, 5],
       [4, 8, 9],
       [1, 7, 9]])

array([[6, 5],
       [8, 9],
       [7, 9]])