In [108]:
import numpy as np
from scipy.stats import skewnorm, skew
import matplotlib.pyplot as plt


#parameters
classes = [0.2, 0.5, 0.3] #percentages
n_vars = 5
n = 79
max_mu = 20
max_sigma = 10
max_skew = 7
np.random.seed(12345)


def simulate_data(classes, n_vars, n, max_mu, max_sigma, max_skew):
    #The multivariate skew normal number generator
    def rng(mu, sigma, skew, n=1):
        k = len(mu)
        if not (k == len(sigma) and k ==len(skew)): 
            raise Exception("Mu, Sigma and Skew should be same length")

        data = np.zeros((int(n),k))

        for i in range(k):
            data[:,i] = skewnorm.rvs(skew[i], loc=mu[i], scale=sigma[i], size=int(n)) 

        return data
    
    if(np.sum(classes) != 1):
        raise Exception("Classes dont sum up to 1")
        
    n_classes = len(classes)
    sigma = np.random.randint(1,max_sigma,n_vars)
    skew = np.random.randint(-max_skew,max_skew,n_vars)
    mu =  np.random.randint(-max_mu, max_mu, (n_classes, n_vars))
    
    n_obs_class = np.round(np.dot(classes,n))
    
    
    for i in range(n_classes):
         print(rng(mu[i,:], sigma, skew, n_obs_class[i]))
        
    
    X = np.zeros(2)
    y= np.zeros(2)
    return X,y

X,y = simulate_data(classes, n_vars, n, max_mu, max_sigma, max_skew)
# data = X.join(pd.Series(y, name='class'))

# display(data.head())
display(X)
display(y)


[[ -9.1070274    8.28681257  -7.98852688 -19.00632401 -12.92109247]
 [ -8.31960545  10.36091477  -7.08659016 -15.73368548 -13.60912078]
 [ -6.04077663  18.25530031  -4.75467377 -15.42278056 -10.68573033]
 [ -7.18500572  12.87960741  -5.03634324 -16.14031767  -9.15770271]
 [ -9.02973093  12.26549223  -5.83482569 -13.99316601 -10.53535977]
 [ -8.71781244  12.51128157  -5.30812363 -16.36050299 -11.80462769]
 [-10.13144487  10.74282403  -4.49541602 -13.38986894  -8.49806764]
 [-10.08200155  12.6263565   -3.75491634 -11.83122076  -9.56801504]
 [ -7.92817198  16.22444365  -6.89909957 -14.96952494 -10.73403153]
 [ -8.93079079   8.61203502  -7.70536315 -16.84342132 -19.09796435]
 [ -6.45334066  15.88856894  -4.67584267 -10.5215036  -10.14646394]
 [ -5.24967646  14.7405749   -7.02119819 -11.588012   -18.34463171]
 [ -7.62190078  15.73204483  -5.02651656 -14.35048043 -17.91061847]
 [ -9.9567404   12.86011573  -7.07895178 -12.46772373  -9.78709837]
 [ -5.97729093   8.66756349  -7.16151003 -13.291

array([0., 0.])

array([0., 0.])

In [ ]:
    
    

# display(np.cov(data.T))




# plt.plot(x, y, 'x')
# plt.axis('equal')
# plt.show()


# plt.hist(x)
# plt.hist(y)
# # plt.hist(z)

# from mpl_toolkits import mplot3d
# fig = plt.figure()
# ax = plt.axes(projection='3d')
# ax.scatter3D(x, y, z, c=z);